### ISSUE TITLE
How to attach UART with this library?

### ISSUE THREAD

**Issue by Eplankton** [Viatorus/emio#66]

**Comment by Viatorus** [comment]
Hello @Eplankton and thank you for your question.

The exact usage depends on the HAL of your UART. Here is an example.

## Example

Assuming you are using a HAL like STM32s UART (https://wiki.st.com/stm32mcu/wiki/Getting_started_with_UART).

There should exists functions like `int uart_receive_bytes(char* buffer, size_t length)` and `void uart_write_bytes(const char*buffer, size_t length)`.

### Format

#### Straight forward

```cpp
std::string str = emio::format("Hello world, {}!", 42);
uart_write_bytes(str.data(), str.size());
```

#### Optimized using a custom buffer

The buffer will write out the data through the UART if flush is called or the internal cache is full.

```cpp
class uart_buffer : public emio::buffer {
public:
  explicit uart_buffer() noexcept {
    this->set_write_area(cache_);
  }

  void flush() noexcept {
    uart_write_bytes(cache_.data(), this->get_used_count());
    this->set_write_area(cache_);
  }

protected:
  emio::result<std::span<char>> request_write_area(const size_t /*used*/, const size_t size) noexcept override {
    flush()
    const std::span<char> area{cache_};
    this->set_write_area(area);
    if (size > cache_.size()) {
      return area;
    }
    return area.subspan(0, size);
  }

 private:
  std::array<char, emio::default_cache_size> cache_;
};

int main() {
  uart_buffer buf;
  emio::format_to(buf, "Hello world, {}!", 42).value();

  emio::format_to(buf, "Let's continue!").value();

  buf.flush();  // Don't forget to flush!
}
```

### scan

```cpp
std::array<char, 128> storage;
// Assuming message: "I am 42 years old!"
const size_t bytes_read = uart_receive_bytes(storage.data(), storage.size()); 

emio::reader rdr{storage.data(), bytes_read};
int age{};
emio::scan_from(rdr, "I am {} years old!", age).value();
```

**Comment by dns13** [comment]
When working on embedded you may also retarget your writes by providing (a C linked) `_write()` function to use `emio::print` or `emio::println`:

```c++
auto _write(int file, const char* ptr, size_t len) -> int {
	switch (file) {
		case 1: UART::writeBytes(ptr, len); break;
		case 2: UDP::writeBytes(ptr, static_cast<int>(len)); break;
		case 3: mqttPrintDebug({ptr, len}); break;
		default: return -1;
	}

	return static_cast<int>(len);
}
```

**Comment by Eplankton** [comment]
> When working on a bare metal target you may also retarget your writes by providing a (C linked) `_write()` function to use `emio::print` or `emio::println`:
> 
> ```c++
> auto _write(int file, const char* ptr, size_t len) -> int {
> 	switch (file) {
> 		case 1: UART::writeBytes(ptr, len); break;
> 		case 2: UDP::writeBytes(ptr, static_cast<int>(len)); break;
> 		case 3: mqttPrintDebug({ptr, len}); break;
> 		default: return -1;
> 	}
> 
> 	return static_cast<int>(len);
> }
> ```

Thanks, and if I wish to use emio::scan, what should I do then?

**Comment by dns13** [comment]
Never done input, but I think retargeting _read_r() would be the way.

https://community.st.com/t5/stm32-mcus-products/retarget-scanf-stm32-atollic/m-p/557775

**Comment by Viatorus** [comment]
emio::scan doesn't work directly with infinity streams like cin/read_r.

You have to provide an own flow-control when a message starts and end (e.g. after a line break) and than scan this message with emio::scan as finite string.

**Comment by Viatorus** [comment]
I am closing this issue as it has either been solved or stale. If this is not the case, please feel free to open it again.
