### ISSUE TITLE
Plain strings passed to emio::print variants are repeated after 128 bytes

### ISSUE THREAD

**Issue by dns13** [Viatorus/emio#68]
When printing with `emio::print` or `emio::println` with a format string longer than 128 byte, the string is repeated from the beginning after those 128 bytes. This does not happen for `emio::format` ~~or printing with a format specifier~~.

See example here: https://godbolt.org/z/KG5ddfvvM

**Comment by dns13** [comment]
I must correct me, it also does not work for non plain strings, it just starts later as the format string is shorter in my example.

**Comment by dns13** [comment]
It seems to be limited by the default size, when I increase it to my needs it works as expected. Maybe a flush in between when buffer is full?

`inline constexpr size_t default_cache_size{128};`

**Comment by Viatorus** [comment]
Thank you for using/trying out emio and reporting this bug. :)

It should be fixed now.

**Comment by dns13** [comment]
Thanks for that quick response!
