### ISSUE TITLE
Return number of characters written instead of result<void>

### ISSUE THREAD

**Issue by dudoslav** [Viatorus/emio#81]
Hi,

I need to know the number of characters used when formatting int and I have noticed that there is no other way other than using `formatted_size` which is nice but isn't calling an extra function to calculate number of serialized characters redundant?

My idea is to change all `write_*` member function on `writer` class to return `std::size_t` of number of written characters instead of `void`. Is that OK? I can make these changes myself and create PR if needed.

**Comment by Viatorus** [comment]
Hello,
thank you for using emio. :)

`formatted_size` is part of the high-level API which matches with `format/format_to`.

Do you have an example why do you need those sizes?

**Comment by dudoslav** [comment]
Hi again,
no problem the library is awesome.

Well, I am using it to serialize JSON into buffer of arbitrary size. The issue is that the API I have to provide needs to return the number of bytes written. I can do that using `formatted_size` but I kind of wanted to simply return the result of `format_to` to not waste time computing the size.

I might not be aware of all library's features. And, also standard's library `printf` and its friends all return the number of characters written so it might be even helpful for someone else. I can provide some kind code example if it is needed, later today :).

**Comment by Viatorus** [comment]
@dudoslav how did you solve your issue? Do you still need the length as return?
