### ISSUE TITLE
Freestanding support

### ISSUE THREAD

**Issue by ra-kal** [Viatorus/emio#90]
Hi,

I'm searching for an {fmt} like formatting library that works in freestanding environment (no OS, gcc -ffreestanding option). {fmt} is rather heavy and it would be very difficult to restrict it to freestanding environment. But it is easy for em{io}, it is just necessary to disable <string> and <stdexcept> includes and support for std::string.

**Comment by Viatorus** [comment]
Thank you for your request. Should be working with freestanding now. Let me know if not. ;)
