### ISSUE TITLE
Formating string requires to be constant expression

### ISSUE THREAD

**Issue by ra-kal** [Viatorus/emio#91]
I'm trying create a logging function using em{io}. It should write srouce level and code location to the output string before the formatted string.

Here the code, which does not compile:

```
struct format_string_with loc
{
  template<typename T>
  format_string(const T& s, const std::source_location& l = std::source_location::current()) :
      str(s), loc(l)
      {}

  std::string_view str;
  std::source_location loc;
};

template<typename... Args>
void debug(const format_string_with_loc& format, Args&&... args)
{
  using namespace emio;
  auto buffer = static_buffer<120>{};
  auto out = writer{buffer};
  static_cast<void>(out.write_str("DBG"));

  const auto& loc = format.loc;
  static_cast<void>(format_to(out, " {}:{}: ", loc.file_name(), loc.line()));
  static_cast<void>(format_to(out, format.str, std::forward<Args>(args)...));

  auto str = buffer.view();
  write_to_uart(str.data(), str.size());
}

int main()
{
  debug("The answer is {}", 42);
}
```

Fails with `error: 'format' is not a constant expression`

Now the issue is, that format_to requires the format string to be constant expression, which I'm not able to achieve. I tried to use the `emio::format_string` instead of std::string_view to store the format string inside `format_string_with_loc`, but then it needs to be also templated class and gcc fails to deduce the arguments when calling `debug`.

**Comment by ra-kal** [comment]
I see there is a `vformat_to` function, that should solve it, but the `make_format_args` again requires constexpr format. I suppose this is a bug. The same method works with {fmt} and its `vprintf`.

**Comment by Viatorus** [comment]
I didn't checked your whole code but from my understanding, you have to write `emio::runtime(format.str)`. I am quit sure that newer versions of {fmt} require the same thing - a runtime format string must be put into `fmt::runtime`.

Keep in mind that `static_cast<void>` ignores any errors. Better use `.value()`, even for void types.

**Comment by ra-kal** [comment]
With {fmt} it is possible to call vformat_to just with args wrapped by make_format_args:

`fmt::format_to(out, format, fmt::make_format_args(args...));`

Anyway I would still like to have it compile time checked, rather than in runtime.

For now I found a workaround using templated class and deduction guide. But I do not like the fact, that the debug() is not a function;

```
namespace detail {

static inline void log(std::string_view level, std::source_location loc, const emio::format_args& args)
{
  auto buffer = emio::static_buffer<120>{};
  auto out = emio::writer{buffer};

  static_cast<void>(out.write_str(level));
  static_cast<void>(emio::format_to(out, " {} {}: ", loc.file_name(), loc.line()));
  static_cast<void>(emio::vformat_to(out, args));
  static_cast<void>(out.write_char('\n'));

  const auto& str = buffer.view();
  write_to_console(1, str.data(), str.size());
}
}

template<typename... Args>
struct debug
{
    debug(emio::format_string<Args...> format, Args&&... args, std::source_location loc = std::source_location::current())
    {
      detail::log("DBG", std::move(loc), emio::make_format_args(format, std::forward<Args>(args)...));
    }
};

template <typename... Ts>
debug(const char*, Ts&&...) -> debug<Ts...>;

int main()
{
  debug('test {}', 42);
}
```

Instead, I would like to extend the emio::format_string by source_location:

```
template<typename...Args>
struct format_string_with loc : public emio::format_string<Args...>
{
  template<typename T>
  format_string(const T& s, const std::source_location& l = std::source_location::current()) :
      emio::format_string<Args...>(s), loc(l)
      {}

  std::string_vie str;
};

template<typename...Args>
void debug(format_string_with_loc<Args...> format, Args&&... args)
{
....
}
```
But this code does not compile:
`mismatched types 'format_string_with_loc<Args ...>' and 'const char*'`

I can't figure, how the deduction works with emio::format_string<Args...>. If I replace my format_string_with_loc with emio::format_string, the code compiles.

**Comment by ra-kal** [comment]
OK, I figured it out!
I need to use type_identity_t in the function signature!

`void debug(detail::format_string_with_location<std::type_identity_t<Args>...> format, Args&&...args)`

**Comment by Viatorus** [comment]
I am closing this issue as it has either been solved or stale. If this is not the case, please feel free to open it again
